changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking changes
      labels: [breaking-change]
    - title: Features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Amazon model updates
      labels: [sp-api-models]
    - title: Dependencies
      labels: [dependencies]
    - title: Other changes
      labels: ["*"]
